quarkus.application.name=twm-calc-service
quarkus.http.port=${EUREKA_REGISTRATION_PORT:8090}

quarkus.stork.twm-calc-py-engine.service-discovery.type=eureka
quarkus.stork.twm-calc-py-engine.service-discovery.eureka-host=localhost
quarkus.stork.twm-calc-py-engine.service-discovery.eureka-port=2012
quarkus.stork.twm-calc-py-engine.service-discovery.application=twm-calc-py-engine

quarkus.rest-client."twm-calc-py-engine".url=stork://twm-calc-py-engine
quarkus.rest-client."twm-calc-py-engine".connect-timeout=10000
quarkus.rest-client."twm-calc-py-engine".read-timeout=10000

# Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Eureka Registration
quarkus.eureka.enable=true
quarkus.eureka.service-url.default=http://localhost:2012/eureka/
quarkus.eureka.port=${EUREKA_REGISTRATION_PORT:8090}
quarkus.eureka.instance-id=${quarkus.application.name}:${quarkus.eureka.port}
quarkus.eureka.heartbeat.enabled=true
quarkus.eureka.heartbeat.health-path=/q/health
quarkus.eureka.prefer-ip-address=true
